/**
 * Owner: Dev 3. Ticket: "ElevenLabs SFX pack".
 * Sounds generated by backend/scripts/render_sfx.py, triggered from game events.
 */
import { gameEvents } from "../game/events";
import { audioEngine } from "./audioEngine";

export const SFX_BASE = "/sfx/";
export type SfxId =
  | "flap"
  | "death"
  | "near_miss"
  | "new_best"
  | "level_up"
  | "heaven";
/** Fast keyboard flapping should not turn into a buzz. */
export const FLAP_GAP_MS = 90;

export function sfxForLevel(
  level: "kitchen" | "dessert" | "heaven",
  altitude: number,
): SfxId | null {
  if (level === "heaven") {
    return "heaven";
  }
  return altitude > 0 ? "level_up" : null;
}

export function playSfx(id: SfxId): void {
  audioEngine.play(`${SFX_BASE}${id}.mp3`, "sfx");
}

export function installSfx(): () => void {
  let lastFlapMs = Number.NEGATIVE_INFINITY;
  for (const id of [
    "flap",
    "death",
    "near_miss",
    "new_best",
    "level_up",
    "heaven",
  ] satisfies SfxId[]) {
    audioEngine.prefetch(`${SFX_BASE}${id}.mp3`);
  }
  const remove = [
    gameEvents.on("flap", () => {
      const now = performance.now();
      if (now - lastFlapMs >= FLAP_GAP_MS) {
        lastFlapMs = now;
        playSfx("flap");
      }
    }),
    gameEvents.on("death", () => playSfx("death")),
    gameEvents.on("near_miss", () => playSfx("near_miss")),
    gameEvents.on("new_best", () => playSfx("new_best")),
    gameEvents.on("level_start", (event) => {
      const id = sfxForLevel(event.level, event.altitude);
      if (id) {
        playSfx(id);
      }
    }),
  ];
  return () => {
    for (const off of remove) {
      off();
    }
  };
}
